# Generated by Django 5.2.4 on 2025-07-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_comment'),
        ('todo', '0002_task_priority'),
    ]

    operations = [
    ]
